name: flutter_data_persistence_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # My
  flutter_common_package:
    git:
      url: https://github.com/wjprogramer/flutter_common_package
      ref: ce322d3

  # MIT
  # Android iOS Linux macOS web Windows
  moor: ^4.5.0
  # Android iOS macOS
  sqlite3_flutter_libs: ^0.5.0

  # BSD
  # Android iOS Linux macOS web Windows
  path: ^1.8.0
  # Android iOS Linux macOS Windows
  path_provider: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # MIT
  moor_generator: ^4.5.1
  # BSD
  build_runner: ^2.1.2

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/